spring:
  application:
    name: proctoring-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/proctoring_bot
    username: proctoring_bot
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  task:
    scheduling:
      pool:
        size: 5

bot:
  name: proctoring-bot
  token: <TOKEN>
  email: <EMAIL>

google:
  application:
    name: ProctoringBot
  sheets:
    table-id: <TABLE_ID>
  credentials:
    path: src/main/resources/tokens/proctoringbot.json

job:
  cron:
    test-start: "0 * * * * *"