spring:
  application:
    name: proctoring-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/proctoring_bot
    username: proctoring_bot
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  task:
    scheduling:
      pool:
        size: 5

bot:
  name: proctoring-bot
  token: 7821697535:AAFM31HTXw5rVH76mHF1XHijPiR1NfmUdw8
  email: <EMAIL>

google:
  application:
    name: ProctoringBot
  sheets:
    table-id: 1Cr9aGwaU2X-qMVeVDM04c_mTSrZGqcIhj4UiqsS3ikA
  credentials:
    path: src/main/resources/tokens/proctoringbot.json

job:
  cron:
    test-start: "0 * * * * *"
    test-check: "0 */30 * * * *"