volumes:
  pgdata:
    driver: local

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/proctoring-bot/data/pgdata
    environment:
      POSTGRES_DB: proctoring_bot
      POSTGRES_USER: proctoring_bot
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"